# Generated by Django 5.0.1 on 2024-04-28 21:29

import car_trader.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='horsepower',
            field=car_trader.core.validators.MyCustomIntegerField(default='100'),
        ),
    ]
