# Generated by Django 5.0.1 on 2024-05-05 05:24

import car_trader.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_horsepower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=car_trader.core.validators.MyCustomIntegerField(blank=True, null=True),
        ),
    ]
