# Generated by Django 5.0.2 on 2024-02-18 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_carbrand_ad_abs_checkbox_ad_brand_ad_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='horsepower',
            field=models.IntegerField(default='0', validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(default='0', validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
