# Generated by Django 5.0.2 on 2024-02-18 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_ad_horsepower_alter_ad_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='brand',
            field=models.CharField(choices=[('default', 'default'), ('BMW', 'BMW'), ('Audi', 'Audi')], default='default'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='horsepower',
            field=models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='info',
            field=models.CharField(default='valEue', max_length=10),
        ),
        migrations.AlterField(
            model_name='ad',
            name='model',
            field=models.CharField(blank=True, choices=[('BMW', [('X1', 'X1'), ('X2', 'X2')]), ('Audi', [('A1', 'A1'), ('A2', 'A2')])]),
        ),
    ]
