# Generated by Django 5.0.2 on 2024-02-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_ad_horsepower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='horsepower',
            field=models.CharField(),
        ),
    ]
