# Generated by Django 5.0.2 on 2024-02-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_ad_horsepower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='horsepower',
            new_name='horse_power',
        ),
    ]
