# Generated by Django 5.0.2 on 2024-02-18 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_rename_horsepower_ad_horse_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='horse_power',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
