# Generated by Django 5.0.2 on 2024-02-18 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_ad_horse_power_alter_ad_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
