# Generated by Django 5.0.2 on 2024-02-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_ad_horse_power_alter_ad_color_alter_ad_coupe_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='color',
            field=models.CharField(choices=[('default', 'default'), ('Banana', 'Банан'), ('Beige', 'Бежов'), ('Bordeaux', 'Бордо'), ('Bronze', 'Бронзов'), ('White', 'Бял'), ('Violet', 'Виолетов'), ('Yellow', 'Жълт'), ('Green', 'Зелен'), ('Golden', 'Златист'), ('Brown', 'Кафяв'), ('Terracotta', 'Керемиден'), ('Orange', 'Оранжев'), ('Gray', 'Сив'), ('Blue', 'Син'), ('Silver', 'Сребърен'), ('Red', 'Червен'), ('Black', 'Черен'), ('Lilac', 'Лилав'), ('Pearl', 'Перла'), ('Pink', 'Розов'), ('Chameleon', 'Хамелеон'), ('Light Green', 'Светло Зелен'), ('Light Gray', 'Светло Сив'), ('Light Blue', 'Светло Син'), ('Dark Green', 'Тъмно Зелен'), ('Dark Gray', 'Тъмно Сив'), ('Dark Blue', 'Тъмно Син')], default='default'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='coupe_type',
            field=models.CharField(choices=[('Van', 'Ван'), ('Jeep', 'Джип'), ('Cabrio', 'Кабрио'), ('Kombi', 'Комби'), ('Coupe', 'Купе'), ('Minivan', 'Миниван'), ('Pickup', 'Пикап'), ('Sedan', 'Седан'), ('Hatchback', 'Хечбекан')], default='Van'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EURO', 'EURO'), ('Lev', 'Лева')], default='USD'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='engine',
            field=models.CharField(choices=[('Engine', 'Двигател'), ('Gasoline', 'Бензинов'), ('Diesel', 'Дизелов'), ('Electric', 'Електрически'), ('Hybrid', 'Хибриден'), ('Plug-in Hybrid', 'Plug-in Хибрид')], default='Engine'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='eurostandard',
            field=models.CharField(choices=[('Euro 1', 'Евро 1'), ('Euro 2', 'Евро 2'), ('Euro 3', 'Евро 3'), ('Euro 4', 'Евро 4'), ('Euro 5', 'Евро 5'), ('Euro 6', 'Евро 6')], default='Euro 1'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='gearbox',
            field=models.CharField(choices=[('Automatic', 'Автоматична'), ('Manual', 'Ръчна')], default='Automatic'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='month_of_production',
            field=models.CharField(choices=[('January', 'Януари'), ('February', 'Февруари'), ('March', 'Март'), ('April', 'Април'), ('May', 'Май'), ('June', 'Юни'), ('July', 'Юли'), ('August', 'Август'), ('September', 'Септември'), ('October', 'Октомври'), ('November', 'Ноември'), ('December', 'Декември')], default='January'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='region',
            field=models.CharField(choices=[('Blagoevgrad', 'Благоевград'), ('Burgas', 'Бургас'), ('Varna', 'Варна'), ('Veliko Turnovo', 'Велико Търново'), ('Vidin', 'Видин'), ('Vratsa', 'Враца'), ('Gabrovo', 'Габрово'), ('Dobrich', 'Добрич'), ('Dupnitsa', 'Дупница'), ('Kardzhali', 'Кърджали'), ('Kyustendil', 'Кюстендил'), ('Lovech', 'Ловеч'), ('Montana', 'Монтана'), ('Pazardzhik', 'Пазарджик'), ('Pernik', 'Перник'), ('Pleven', 'Плевен'), ('Plovdiv', 'Пловдив'), ('Razgrad', 'Разград'), ('Ruse', 'Русе'), ('Silistra', 'Силистра'), ('Sliven', 'Сливен'), ('Smolyan', 'Смолян'), ('Sofia', 'София'), ('Stara Zagora', 'Стара Загора'), ('Targovishte', 'Търговище'), ('Haskovo', 'Хасково'), ('Shumen', 'Шумен'), ('Yambol', 'Ямбол')], default='Blagoevgrad'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='wheel',
            field=models.CharField(choices=[('Left', 'Ляв'), ('Right', 'Десен')], default='Left'),
        ),
    ]
