# Generated by Django 5.0.2 on 2024-02-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_ad_color_alter_ad_coupe_type_alter_ad_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
