# Generated by Django 5.0.2 on 2024-02-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_alter_ad_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='info',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
