# Generated by Django 5.0.2 on 2024-02-18 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_ad_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='horse_power',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
