# Generated by Django 5.0.2 on 2024-02-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_alter_ad_horse_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='horse_power',
        ),
    ]
