# Generated by Django 5.0.2 on 2024-02-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_remove_ad_horse_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(choices=[('default', 'default'), ('BMW', 'BMW'), ('Audi', 'Audi')], default='Model'),
        ),
    ]
