# Generated by Django 5.0.2 on 2024-02-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_carbrand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(choices=[('default', 'default'), ('BMW', 'BMW'), ('Audi', 'Audi')], default='default'),
        ),
    ]
