# Generated by Django 5.0.2 on 2024-02-18 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_ad_horse_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.carbrand'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.carmodel'),
        ),
    ]
