# Generated by Django 5.0.2 on 2024-02-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_ad_brand_alter_ad_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='horse_power',
        ),
    ]
