# Generated by Django 5.0.2 on 2024-02-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_remove_ad_horse_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='abs_checkbox',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='color',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='coupe_type',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='eurostandard',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='gearbox',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='month_of_production',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='region',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='wheel',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='year_of_production',
        ),
    ]
