# Generated by Django 5.0.2 on 2024-02-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_ad_abs_checkbox_ad_color_ad_coupe_type_ad_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='CarBrand',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
