# Generated by Django 5.0.2 on 2024-02-18 19:45

import car_trader.web.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_remove_carmodel_brand_delete_ad_delete_carbrand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('default', 'default'), ('BMW', 'BMW'), ('Audi', 'Audi')], default='default')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, max_length=10)),
                ('engine', models.CharField(choices=[('Engine', 'Двигател'), ('Gasoline', 'Бензинов'), ('Diesel', 'Дизелов'), ('Electric', 'Електрически'), ('Hybrid', 'Хибриден'), ('Plug-in Hybrid', 'Plug-in Хибрид')], default='Engine')),
                ('horse_power', car_trader.web.validators.MyCustomIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('eurostandard', models.CharField(choices=[('Euro 1', 'Евро 1'), ('Euro 2', 'Евро 2'), ('Euro 3', 'Евро 3'), ('Euro 4', 'Евро 4'), ('Euro 5', 'Евро 5'), ('Euro 6', 'Евро 6')], default='Euro 1')),
                ('gearbox', models.CharField(choices=[('Automatic', 'Автоматична'), ('Manual', 'Ръчна')], default='Automatic')),
                ('coupe_type', models.CharField(choices=[('Van', 'Ван'), ('Jeep', 'Джип'), ('Cabrio', 'Кабрио'), ('Kombi', 'Комби'), ('Coupe', 'Купе'), ('Minivan', 'Миниван'), ('Pickup', 'Пикап'), ('Sedan', 'Седан'), ('Hatchback', 'Хечбекан')], default='Van')),
                ('price', car_trader.web.validators.MyCustomIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000)])),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EURO', 'EURO'), ('Lev', 'Лева')], default='USD')),
                ('mileage', car_trader.web.validators.MyCustomIntegerField(blank=True, null=True)),
                ('wheel', models.CharField(choices=[('Left', 'Ляв'), ('Right', 'Десен')], default='Left')),
                ('doors', models.CharField(choices=[('2/3', '2/3'), ('4/5', '4/5'), ('7', '7')], default='2/3')),
                ('month_of_production', models.CharField(choices=[('January', 'Януари'), ('February', 'Февруари'), ('March', 'Март'), ('April', 'Април'), ('May', 'Май'), ('June', 'Юни'), ('July', 'Юли'), ('August', 'Август'), ('September', 'Септември'), ('October', 'Октомври'), ('November', 'Ноември'), ('December', 'Декември')], default='January')),
                ('year_of_production', models.CharField(choices=[('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], default='1990')),
                ('color', models.CharField(choices=[('default', 'default'), ('Banana', 'Банан'), ('Beige', 'Бежов'), ('Bordeaux', 'Бордо'), ('Bronze', 'Бронзов'), ('White', 'Бял'), ('Violet', 'Виолетов'), ('Yellow', 'Жълт'), ('Green', 'Зелен'), ('Golden', 'Златист'), ('Brown', 'Кафяв'), ('Terracotta', 'Керемиден'), ('Orange', 'Оранжев'), ('Gray', 'Сив'), ('Blue', 'Син'), ('Silver', 'Сребърен'), ('Red', 'Червен'), ('Black', 'Черен'), ('Lilac', 'Лилав'), ('Pearl', 'Перла'), ('Pink', 'Розов'), ('Chameleon', 'Хамелеон'), ('Light Green', 'Светло Зелен'), ('Light Gray', 'Светло Сив'), ('Light Blue', 'Светло Син'), ('Dark Green', 'Тъмно Зелен'), ('Dark Gray', 'Тъмно Сив'), ('Dark Blue', 'Тъмно Син')], default='default')),
                ('region', models.CharField(choices=[('Blagoevgrad', 'Благоевград'), ('Burgas', 'Бургас'), ('Varna', 'Варна'), ('Veliko Turnovo', 'Велико Търново'), ('Vidin', 'Видин'), ('Vratsa', 'Враца'), ('Gabrovo', 'Габрово'), ('Dobrich', 'Добрич'), ('Dupnitsa', 'Дупница'), ('Kardzhali', 'Кърджали'), ('Kyustendil', 'Кюстендил'), ('Lovech', 'Ловеч'), ('Montana', 'Монтана'), ('Pazardzhik', 'Пазарджик'), ('Pernik', 'Перник'), ('Pleven', 'Плевен'), ('Plovdiv', 'Пловдив'), ('Razgrad', 'Разград'), ('Ruse', 'Русе'), ('Silistra', 'Силистра'), ('Sliven', 'Сливен'), ('Smolyan', 'Смолян'), ('Sofia', 'София'), ('Stara Zagora', 'Стара Загора'), ('Targovishte', 'Търговище'), ('Haskovo', 'Хасково'), ('Shumen', 'Шумен'), ('Yambol', 'Ямбол')], default='Blagoevgrad')),
                ('abs_checkbox', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.carbrand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.carmodel')),
            ],
        ),
    ]
