# Generated by Django 5.0.2 on 2024-02-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_carbrand_carmodel_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='horse_power',
        ),
    ]
