# Generated by Django 5.0.2 on 2024-02-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_alter_ad_mileage_alter_ad_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='CarBrand',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
