# Generated by Django 5.0.2 on 2024-02-21 16:48

import car_trader.web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0045_alter_ad_mileage_alter_ad_price_alter_carbrand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='brand',
        ),
        migrations.AlterField(
            model_name='ad',
            name='brand',
            field=models.CharField(choices=[('BMW', 'BMW'), ('Toyota', 'Toyota')]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='model',
            field=models.CharField(choices=[('X1', 'X1'), ('X5', 'X5')]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='mileage',
            field=car_trader.web.models.MyCustomIntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=car_trader.web.models.MyCustomIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.DeleteModel(
            name='CarBrand',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
