# Generated by Django 5.0.2 on 2024-02-21 21:19

import car_trader.web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_remove_carmodel_brand_alter_ad_brand_alter_ad_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='brand',
            field=models.CharField(choices=[('BMW', 'BMW'), ('Alfa Romeo', 'Alfa Romeo'), ('Toyota', 'Toyota')]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='mileage',
            field=car_trader.web.models.MyCustomIntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='model',
            field=models.CharField(choices=[('X1', 'X1'), ('X5', 'X5'), ('145', '145')]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=car_trader.web.models.MyCustomIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10, message='Телефонният номер трябва да бъде с дължина от 10 цифри')]),
        ),
    ]
