# Generated by Django 5.0.2 on 2024-02-23 20:02

import car_trader.web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_alter_ad_brand_alter_ad_mileage_alter_ad_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='', upload_to=car_trader.web.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='ad',
            name='color',
            field=models.CharField(choices=[('Banana', 'Банан'), ('Beige', 'Бежов'), ('Bordeaux', 'Бордо'), ('Bronze', 'Бронзов'), ('White', 'Бял'), ('Violet', 'Виолетов'), ('Yellow', 'Жълт'), ('Green', 'Зелен'), ('Golden', 'Златист'), ('Brown', 'Кафяв'), ('Terracotta', 'Керемиден'), ('Orange', 'Оранжев'), ('Gray', 'Сив'), ('Blue', 'Син'), ('Silver', 'Сребърен'), ('Red', 'Червен'), ('Black', 'Черен'), ('Lilac', 'Лилав'), ('Pearl', 'Перла'), ('Pink', 'Розов'), ('Chameleon', 'Хамелеон'), ('Light Green', 'Светло Зелен'), ('Light Gray', 'Светло Сив'), ('Light Blue', 'Светло Син'), ('Dark Green', 'Тъмно Зелен'), ('Dark Gray', 'Тъмно Сив'), ('Dark Blue', 'Тъмно Син')], default='Banana'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='mileage',
            field=car_trader.web.models.MyCustomIntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=car_trader.web.models.MyCustomIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
