# Generated by Django 5.0.2 on 2024-02-28 09:42

import car_trader.web.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0051_alter_ad_abs_checkbox_alter_ad_mileage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='images',
        ),
        migrations.AlterField(
            model_name='ad',
            name='abs_checkbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ad',
            name='mileage',
            field=car_trader.web.models.MyCustomIntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=car_trader.web.models.MyCustomIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
