# Generated by Django 5.0.2 on 2024-02-28 09:47

import car_trader.web.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0052_remove_ad_images_alter_ad_abs_checkbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='mileage',
            field=car_trader.web.models.MyCustomIntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=car_trader.web.models.MyCustomIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ad_images/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web.ad')),
            ],
        ),
    ]
