# Generated by Django 5.0.2 on 2024-02-28 17:50

import car_trader.web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_ad_images_alter_ad_mileage_alter_ad_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='color',
            field=models.CharField(choices=[('Банан', 'Банан'), ('Бежов', 'Бежов'), ('Бордо', 'Бордо'), ('Бронзов', 'Бронзов'), ('Бял', 'Бял'), ('Виолетов', 'Виолетов'), ('Жълт', 'Жълт'), ('Зелен', 'Зелен'), ('Златист', 'Златист'), ('Кафяв', 'Кафяв'), ('Керемиден', 'Керемиден'), ('Оранжев', 'Оранжев'), ('Сив', 'Сив'), ('Син', 'Син'), ('Сребърен', 'Сребърен'), ('Червен', 'Червен'), ('Черен', 'Черен'), ('Лилав', 'Лилав'), ('Перла', 'Перла'), ('Розов', 'Розов'), ('Хамелеон', 'Хамелеон'), ('Светло Зелен', 'Светло Зелен'), ('Светло Сив', 'Светло Сив'), ('Светло Син', 'Светло Син'), ('Тъмно Зелен', 'Тъмно Зелен'), ('Тъмно Сив', 'Тъмно Сив'), ('Тъмно Син', 'Тъмно Син')], default='Банан'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='coupe_type',
            field=models.CharField(choices=[('Ван', 'Ван'), ('Джип', 'Джип'), ('Кабрио', 'Кабрио'), ('Комби', 'Комби'), ('Купе', 'Купе'), ('Миниван', 'Миниван'), ('Пикап', 'Пикап'), ('Седан', 'Седан'), ('Хечбек', 'Хечбек')], default='Ван'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('Лева', 'Лева')], default='USD'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='doors',
            field=models.CharField(choices=[('2/3', '2/3'), ('4/5', '4/5')], default='2/3'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='engine',
            field=models.CharField(choices=[('Бензинов', 'Бензинов'), ('Дизелов', 'Дизелов'), ('Електрически', 'Електрически'), ('Хибриден', 'Хибриден'), ('Plug-in Хибрид', 'Plug-in Хибрид')], default='Бензинов'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='eurostandard',
            field=models.CharField(choices=[('Евро 1', 'Евро 1'), ('Евро 2', 'Евро 2'), ('Евро 3', 'Евро 3'), ('Евро 4', 'Евро 4'), ('Евро 5', 'Евро 5'), ('Евро 6', 'Евро 6')], default='Евро 1'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='gearbox',
            field=models.CharField(choices=[('Автоматична', 'Автоматична'), ('Ръчна', 'Ръчна')], default='Автоматична'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='mileage',
            field=car_trader.web.models.MyCustomIntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='month_of_production',
            field=models.CharField(choices=[('Януари', 'Януари'), ('Февруари', 'Февруари'), ('Март', 'Март'), ('Април', 'Април'), ('Май', 'Май'), ('Юни', 'Юни'), ('Юли', 'Юли'), ('Август', 'Август'), ('Септември', 'Септември'), ('Октомври', 'Октомври'), ('Ноември', 'Ноември'), ('Декември', 'Декември')], default='Януари'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=car_trader.web.models.MyCustomIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='region',
            field=models.CharField(choices=[('Благоевград', 'Благоевград'), ('Бургас', 'Бургас'), ('Варна', 'Варна'), ('Велико Търново', 'Велико Търново'), ('Видин', 'Видин'), ('Враца', 'Враца'), ('Габрово', 'Габрово'), ('Добрич', 'Добрич'), ('Дупница', 'Дупница'), ('Кърджали', 'Кърджали'), ('Кюстендил', 'Кюстендил'), ('Ловеч', 'Ловеч'), ('Монтана', 'Монтана'), ('Пазарджик', 'Пазарджик'), ('Перник', 'Перник'), ('Плевен', 'Плевен'), ('Пловдив', 'Пловдив'), ('Разград', 'Разград'), ('Русе', 'Русе'), ('Силистра', 'Силистра'), ('Сливен', 'Сливен'), ('Смолян', 'Смолян'), ('София', 'София'), ('Стара Загора', 'Стара Загора'), ('Търговище', 'Търговище'), ('Хасково', 'Хасково'), ('Шумен', 'Шумен'), ('Ямбол', 'Ямбол')], default='Благоевград'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='wheel',
            field=models.CharField(choices=[('Ляв', 'Ляв'), ('Десен', 'Десен')], default='Ляв'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, choices=[('Благоевград', 'Благоевград'), ('Бургас', 'Бургас'), ('Варна', 'Варна'), ('Велико Търново', 'Велико Търново'), ('Видин', 'Видин'), ('Враца', 'Враца'), ('Габрово', 'Габрово'), ('Добрич', 'Добрич'), ('Дупница', 'Дупница'), ('Кърджали', 'Кърджали'), ('Кюстендил', 'Кюстендил'), ('Ловеч', 'Ловеч'), ('Монтана', 'Монтана'), ('Пазарджик', 'Пазарджик'), ('Перник', 'Перник'), ('Плевен', 'Плевен'), ('Пловдив', 'Пловдив'), ('Разград', 'Разград'), ('Русе', 'Русе'), ('Силистра', 'Силистра'), ('Сливен', 'Сливен'), ('Смолян', 'Смолян'), ('София', 'София'), ('Стара Загора', 'Стара Загора'), ('Търговище', 'Търговище'), ('Хасково', 'Хасково'), ('Шумен', 'Шумен'), ('Ямбол', 'Ямбол')]),
        ),
    ]
