# Generated by Django 5.0.2 on 2024-03-04 17:48

import car_trader.web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0059_rename_abs_checkbox_ad_abs_ad_gps_ad_led_headlights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='brake_assist_system',
        ),
        migrations.AddField(
            model_name='ad',
            name='board_cpu',
            field=models.BooleanField(default=False, verbose_name='Бордкомпютър'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='LED_headlights',
            field=models.BooleanField(default=False, verbose_name='LED фарове'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='adaptive_lights',
            field=models.BooleanField(default=False, verbose_name='Адаптивни светлини'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='air_conditioning',
            field=models.BooleanField(default=False, verbose_name='Климатик'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='airbags',
            field=models.BooleanField(default=False, verbose_name='Airbags'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='alarm',
            field=models.BooleanField(default=False, verbose_name='Аларма'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='alloy_wheels',
            field=models.BooleanField(default=False, verbose_name='Лети джанти'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='auto_start_stop_funtion',
            field=models.BooleanField(default=False, verbose_name='Auto Start-Stop функция'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='bluetooth',
            field=models.BooleanField(default=False, verbose_name='Bluetooth'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='central_locking',
            field=models.BooleanField(default=False, verbose_name='Централно заключване'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='climate_control',
            field=models.BooleanField(default=False, verbose_name='Климатик'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='descent_control',
            field=models.BooleanField(default=False, verbose_name='Система за контрол на спускането'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='differential_lock',
            field=models.BooleanField(default=False, verbose_name='Блокаж на диференциала'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='el_front_screen',
            field=models.BooleanField(default=False, verbose_name='Подгрев на предното стъкло'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='el_mirrors',
            field=models.BooleanField(default=False, verbose_name='Ел. огледала'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='el_seats',
            field=models.BooleanField(default=False, verbose_name='Ел. регулиране на седалките'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='el_wheel',
            field=models.BooleanField(default=False, verbose_name='Отопление на волана'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='el_windows',
            field=models.BooleanField(default=False, verbose_name='Ел. Стъкла'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='four_by_four',
            field=models.BooleanField(default=False, verbose_name='4x4'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='fully_serviced',
            field=models.BooleanField(default=False, verbose_name='Напълно обслужена'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='gas_as_fuel',
            field=models.BooleanField(default=False, verbose_name='Газова уредба'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='isofix',
            field=models.BooleanField(default=False, verbose_name='Isofix'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='keyless',
            field=models.BooleanField(default=False, verbose_name='Безключово палене'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='leasing',
            field=models.BooleanField(default=False, verbose_name='Лизинг'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='metan_as_fuel',
            field=models.BooleanField(default=False, verbose_name='Метанова уредба'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='mileage',
            field=car_trader.web.models.MyCustomIntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='multi_wheel',
            field=models.BooleanField(default=False, verbose_name='Мултифункционален волан'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='navigation',
            field=models.BooleanField(default=False, verbose_name='Навигация'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='paid_casco',
            field=models.BooleanField(default=False, verbose_name='Платено каско'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='paid_tax',
            field=models.BooleanField(default=False, verbose_name='Платен данък'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='parking_sensor',
            field=models.BooleanField(default=False, verbose_name='Парктроник'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=car_trader.web.models.MyCustomIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='seats_7',
            field=models.BooleanField(default=False, verbose_name='7 местна'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='spoiler',
            field=models.BooleanField(default=False, verbose_name='Спойлер'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='steptronic_tiptronic',
            field=models.BooleanField(default=False, verbose_name='Steptronic/Tiptronic'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='traction_control',
            field=models.BooleanField(default=False, verbose_name='Автоконтрол'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='velour_interior',
            field=models.BooleanField(default=False, verbose_name='Велурен салон'),
        ),
    ]
