# Generated by Django 5.0.2 on 2024-04-12 09:39

import car_trader.web.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0063_alter_ad_mileage_alter_ad_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.TextField(default='Въведете описание'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='mileage',
            field=car_trader.web.models.MyCustomIntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=car_trader.web.models.MyCustomIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
